gf-relay.url()

diff --git a/service/vpnet/run b/service/vpnet/run
--- a/service/vpnet/run
+++ b/service/vpnet/run
@@ -5,8 +5,10 @@
 # https://github.com/acrossfw/vpnet
 #
 source "$ACROSSFW_HOME/vpnet-functions.sh"
+vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic
 
 while [ true ]; do
-    echo 'vpnet working...'
-    sleep 3600
+    npm start
+    echo "ERROR: npm start exit with error code $?" >&2
+    sleep 1
 done
