use vpnet module in run

diff --git a/service/ipsec/run b/service/ipsec/run
--- a/service/ipsec/run
+++ b/service/ipsec/run
@@ -4,7 +4,7 @@
 #
 # https://github.com/acrossfw/vpnet
 #
-# Inspired by https://github.com/gaomd/docker-ikev2-vpn-server
+# IPsec - Inspired by https://github.com/gaomd/docker-ikev2-vpn-server
 #
 
 source /acrossfw/vpnet-module.sh
@@ -44,10 +44,9 @@ ipsec::run() {
   # http://wiki.loopop.net/doku.php?id=server:vpn:strongswanonopenvz
   exec /usr/sbin/ipsec start --nofork
   
-  err_code=$?
-  echo "ERROR: ipsec::run error code $err_code"
+  echo "ERROR: ipsec::run exec ipsec exit with error code $?"
   sleep 1
-  exit $err_code
+  exit -1
 }
 
 main "$@"
diff --git a/service/shadowsocks/run b/service/shadowsocks/run
--- a/service/shadowsocks/run
+++ b/service/shadowsocks/run
@@ -1,22 +1,28 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # VPNet.io - Virtual Private Network Essential Toolbox
+#
 # https://github.com/acrossfw/vpnet
 #
 # ShadowSocks
 #
-ss_cmd=ss-server
-exec $ss_cmd -s 0.0.0.0 \
-	-p 8388 \
-	-k "${ADMIN_PASS:-$(hostname)}" \
-	-m "${SHADOWSOCKS_ENCRYPT_METHOD:-aes-256-cfb}" \
-	-t 300 \
-	--fast-open \
-	-d "${DNS:-8.8.8.8}" \
-	-u
+source /acrossfw/vpnet-module.sh
+vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic
 
+main() {
+  ss_cmd=ss-server
+  exec $ss_cmd -s 0.0.0.0 \
+  	-p 8388 \
+  	-k "${ADMIN_PASS:-$(hostname)}" \
+  	-m "${SHADOWSOCKS_ENCRYPT_METHOD:-aes-256-cfb}" \
+  	-t 300 \
+  	--fast-open \
+  	-d "${DNS:-8.8.8.8}" \
+  	-u
 
-err_code=$?
-echo "ERROR: exec $ss_cmd exit with code $err_code"
-sleep 1
-exit $err_code
+  echo "ERROR: exec shadowsocks exited with error code $?"
+  sleep 1
+  exit -1
+}
+
+main "$@"
