bug fix

diff --git a/service/pptp/run b/service/pptp/run
--- a/service/pptp/run
+++ b/service/pptp/run
@@ -39,7 +39,9 @@ CHAP_SECRETS
 # operation not permited inside docker
 # modprobe nf_conntrack_pptp nf_nat_pptp
 
-pptpd --fg
+exec pptpd --fg
 
-echo "pptpd exit with error code $?"
+error_code=$?
+echo "exec pptpd exit with error code $error_code"
 sleep 1
+exit $error_code
diff --git a/service/ssh/run b/service/ssh/run
--- a/service/ssh/run
+++ b/service/ssh/run
@@ -6,36 +6,50 @@
 #
 # SSH
 #
+source /acrossfw/vpnet-module.sh
+vpnet::init_bash ${BASH_SOURCE[0]} # set all the magic
 
-# http://kvz.io/blog/2013/11/21/bash-best-practices/
-set -o errexit
-set -o pipefail
-set -o nounset
-# set -o xtrace
+main() {
+  local arg1=${1:-}
 
-ADD_USER_HOME="/home/$ADMIN_NAME"
-ADD_USER_NAME="$ADMIN_NAME"
-ADD_USER_PASS="$ADMIN_PASS"
+  ssh::init_authorized_keys
+  ssh::init_admin
+#  ssh::init_users
 
-echo "SSH: Create user home if not exist ... "
-[[ -d "$ADD_USER_HOME" ]] || {
-  adduser --quiet --disabled-password -shell /bin/bash --home "$ADD_USER_HOME" --gecos "$ADD_USER_NAME" "$USER_NAME"
+  n=0
+  while [[ true ]]; do
+    ((++n)) # n++ will cause bash exit, because return 0 (???)
+    echo "SSH: Heartbeat #$n ... "
+    sleep 60
+  done
 }
-echo "SSH: Reset password every time ... "
-echo "$ADD_USER_NAME:$ADD_USER_PASS" | chpasswd
 
 # store ssh authorized key(if set)
-[[ -n "$SSH_AUTHORIZED_KEYS" ]] && {
-  echo "SSH: Writing authorized_keys for root ..."
-  SSH_DIR="/root/.ssh"
-  [ -d "$SSH_DIR" ] || mkdir $SSH_DIR && chmod 700 $SSH_DIR
-  echo $SSH_AUTHORIZED_KEYS >> $SSH_DIR/authorized_keys
-  chmod 600 $SSH_DIR/authorized_keys
+ssh::init_authorized_keys() {
+  [[ -n "$SSH_AUTHORIZED_KEYS" ]] && {
+    echo "SSH: Writing authorized_keys for root ..."
+    DOT_SSH_DIR="/root/.ssh"
+    [ -d "$DOT_SSH_DIR" ] || mkdir $DOT_SSH_DIR && chmod 700 $DOT_SSH_DIR
+    echo $SSH_AUTHORIZED_KEYS >> $DOT_SSH_DIR/authorized_keys
+    chmod 600 $DOT_SSH_DIR/authorized_keys
+  }
 }
 
-N=0
-while [[ true ]]; do
-  ((N++))
-  echo "SSH: Heartbeat #$N... "
-  sleep 3600
-done
+ssh::init_admin() {  
+  ADD_USER_HOME="/home/$ADMIN_NAME"
+  ADD_USER_NAME="$ADMIN_NAME"
+  ADD_USER_PASS="$ADMIN_PASS"
+  
+  echo "SSH: Create user home if not exist ... "
+  [[ -d "$ADD_USER_HOME" ]] || {
+    adduser --quiet --disabled-password -shell /bin/bash --home "$ADD_USER_HOME" --gecos "$ADD_USER_NAME" "$ADD_USER_NAME"
+  }
+  echo "SSH: Reset password every time ... "
+  echo "$ADD_USER_NAME:$ADD_USER_PASS" | chpasswd
+}
+
+main "$@"
+
+echo "ERROR: ssh loop error, exited"
+sleep 1
+exit -1
