linting by shellcheck

diff --git a/service/shadowsocks/run b/service/shadowsocks/run
--- a/service/shadowsocks/run
+++ b/service/shadowsocks/run
@@ -5,18 +5,18 @@
 #
 # ShadowSocks
 #
-CMD=ss-server
-exec $CMD -s 0.0.0.0 \
+ss_cmd=ss-server
+exec $ss_cmd -s 0.0.0.0 \
 	-p 8388 \
 	-k "${PASSWORD:-$(hostname)}" \
-	-m ${SHADOWSOCKS_ENCRYPT_METHOD:-aes-256-cfb} \
+	-m "${SHADOWSOCKS_ENCRYPT_METHOD:-aes-256-cfb}" \
 	-t 300 \
 	--fast-open \
-	-d ${DNS:-8.8.8.8} \
+	-d "${DNS:-8.8.8.8}" \
 	-u
 
 
-ERR_RET=$?
-echo "$CMD error with exit code $ERR_RET"
+err_code=$?
+echo "ERROR: exec $ss_cmd exit with code $err_code"
 sleep 1
-exit $ERR_RET
+exit $err_code
diff --git a/service/squid/run b/service/squid/run
--- a/service/squid/run
+++ b/service/squid/run
@@ -12,7 +12,7 @@
 SQUID_CONF=/etc/squid/squid.conf
 SQUID_PASSWD=/etc/squid/htpasswd
 
-htpasswd -b -c $SQUID_PASSWD ${ADMIN_NAME:-vpnet} ${ADMIN_PASS:-vpnet.io}
+htpasswd -b -c "$SQUID_PASSWD" "${ADMIN_NAME:-vpnet}" "${ADMIN_PASS:-vpnet.io}"
 
 cat << SQUID_CONF > $SQUID_CONF
 # http://wiki.squid-cache.org/KnowledgeBase/NoForwardProxyPorts
@@ -80,7 +80,7 @@ SQUID_CONF
 ulimit -n 65535
 exec squid -N -d 1 -YC
 
-ERR_CODE = $?
-echo "ERROR: squid exit code $ERR_CODE"
+err_code=$?
+echo "ERROR: exec squid exit code $err_code"
 
-exit $ERR_CODE
+exit $err_code
diff --git a/service/ssh/run b/service/ssh/run
--- a/service/ssh/run
+++ b/service/ssh/run
@@ -7,13 +7,13 @@
 # SSH
 #
 source /acrossfw/vpnet-module.sh
-vpnet::init_bash ${BASH_SOURCE[0]} # set all the magic
+vpnet::init_bash "${BASH_SOURCE[0]}" # set all the magic
 
 main() {
-  local arg1=${1:-}
+  # local arg1=${1:-}
 
-  ssh::init_authorized_keys
   ssh::init_admin
+  ssh::init_authorized_keys
 #  ssh::init_users
 
   n=0
@@ -27,11 +27,18 @@ main() {
 # store ssh authorized key(if set)
 ssh::init_authorized_keys() {
   [[ -n "$SSH_AUTHORIZED_KEYS" ]] && {
-    echo "SSH: Writing authorized_keys for root ..."
-    for DOT_SSH_DIR in "/home/$ADMIN_NAME/.ssh" "/root/.ssh"; do
-      [ -d "$DOT_SSH_DIR" ] || mkdir $DOT_SSH_DIR && chmod 700 $DOT_SSH_DIR
-      echo $SSH_AUTHORIZED_KEYS >> $DOT_SSH_DIR/authorized_keys
-      chmod 600 $DOT_SSH_DIR/authorized_keys
+    echo "ssh:init_authorized_keys Writing authorized_keys for root & $ADMIN_NAME ..."
+    local user_name
+    local user_home
+    local dot_ssh_dir
+    for user_name in 'root' "$ADMIN_NAME"; do
+      vpnet::get_user_home "$user_name" user_home #|| true # fail safe
+      dot_ssh_dir="$user_home/.ssh/"
+      [ -d "$dot_ssh_dir" ] || mkdir "$dot_ssh_dir"
+      echo "$SSH_AUTHORIZED_KEYS" >> "${dot_ssh_dir}authorized_keys"
+      chmod 700 "${dot_ssh_dir}"
+      chmod 600 "${dot_ssh_dir}authorized_keys"
+      chown -R "$user_name" "$dot_ssh_dir"
     done
   }
 }
@@ -41,7 +48,7 @@ ssh::init_admin() {
   ADD_USER_NAME="$ADMIN_NAME"
   ADD_USER_PASS="$ADMIN_PASS"
   
-  echo "SSH: Create user home if not exist ... "
+  echo "ssh::init_admin Create user home if not exist ... "
   [[ -d "$ADD_USER_HOME" ]] || {
     adduser --quiet --disabled-password -shell /bin/bash --home "$ADD_USER_HOME" --gecos "$ADD_USER_NAME" "$ADD_USER_NAME"
   }
